INSERT INTO messages (body) VALUES
('Contact me at john.doe@gmail.com or support@yandex.ru. Also admin@evil.com and user@mail.ru.'),
('No emails here.'),
('Spam: fake@gmail.org, test@yandex.com.ua, real@mail.ru!'),
('Double: user1@gmail.com and user2@gmail.com in one string.'),
('Edge: @gmail.com is not email, nor gmail.com@, but valid@yandex.ru is.'),
('Send feedback to feedback@gmail.com — we read every message.'),
('Invalid: user@, @mail.ru, mail.ru@user, nothing here.'),
('Valid only: ceo@yandex.ru and dev@mail.ru.'),
('All fake: admin@gmail.net, root@yandex.com, postmaster@mail.org.'),
('One good: only.one.valid@gmail.com in this sentence.'),
('Try me: sales@yandex.ru or marketing@mail.ru for partnerships.'),
('Nothing to see here. Move along.'),
('Hidden: my.real.address.is.secret@gmail.com — shhh!'),
('Typo: user@gmil.com, admim@yandex.ru, suport@mail.ru.'),
('Old school: webmaster@gmail.com, postmaster@yandex.ru, abuse@mail.ru.'),
('International: café@yandex.ru — but actually not valid in basic regex.'),
('With plus: user+promo@gmail.com should be captured.'),
('With dots: first.last@mail.ru is valid.'),
('Subdomain? user@sub.gmail.com — nope, not in our list.'),
('Mixed: valid@gmail.com, invalid@yandex.com.ua, good@mail.ru.'),
('All three: one@gmail.com, two@yandex.ru, three@mail.ru in one row.'),
('None of them valid: @gmail.com, user@, .@mail.ru.'),
('Just noise: !@#$%^&*() — no email.'),
('Empty field between commas: ,, — still no email.'),
('Repeated: test@gmail.com test@gmail.com test@gmail.com.'),
('Long TLD? user@gmail.company — no.'),
('Single char: a@yandex.ru — valid.'),
('Numeric user: 123@mail.ru — valid.'),
('Weird but valid: _.-+!#$%&''*+/=?^`{|}~@gmail.com — yes, really.'),
('Space around:  user@gmail.com  — should still match.'),
('Newlines in string: 
user@yandex.ru
 — still valid.'),
('Tabs:	user@mail.ru	 — still valid.'),
('Mixed case: User@Gmail.Com — should match if using case-insensitive.'),
('All caps: ADMIN@YANDEX.RU — still valid domain.'),
('All lower: support@mail.ru — fine.'),
('Misspelled: gmaill.com, yanddex.ru, maiil.ru.'),
('Almost: user@gmail.сom (cyrillic с) — invalid.'),
('IDN? пользователь@почта.рф — skip, not in scope.'),
('Corporate: hr@company.gmail.com — no, not gmail.com.'),
('Free email only: personal@gmail.com yes, work@mycompany.com no.'),
('Two in one: first@gmail.com and second@mail.ru.'),
('Three domains: a@gmail.com, b@yandex.ru, c@mail.ru.'),
('One invalid, two valid: bad@evil.com, good@yandex.ru, great@mail.ru.'),
('Only invalid: bad@gmail.net, worse@yandex.uk, ugly@mail.xyz.'),
('Only one valid: needle@gmail.com in haystack of text.'),
('Valid at end: this is valid — admin@yandex.ru.'),
('Valid at start: support@mail.ru is who you need.'),
('Surrounded by symbols: !!!user@gmail.com???'),
('In parentheses: (contact@gmail.com) for help.'),
('In brackets: [info@yandex.ru] is monitored.'),
('In quotes: "helpdesk@mail.ru" — still valid.'),
('With comma: write to us, user@gmail.com, soon.'),
('With semicolon: reply;admin@yandex.ru;thanks.'),
('Email in URL? http://user@gmail.com — still an email.'),
('Email as parameter? ?email=support@mail.ru — yes.'),
('Email in JSON: {"email": "user@gmail.com"} — still match.'),
('Email in XML: <email>admin@yandex.ru</email> — yes.'),
('Email with port? user@gmail.com:8080 — no, invalid.'),
('Email with path? user@gmail.com/profile — invalid.'),
('Double at: user@@gmail.com — invalid.'),
('No dot in domain: user@gmailcom — invalid.'),
('Dot at start: .user@gmail.com — invalid local part.'),
('Dot at end: user.@gmail.com — invalid.'),
('Consecutive dots: user..name@gmail.com — invalid.'),
('Starts with dot in domain: user@.gmail.com — invalid.'),
('Ends with dot in domain: user@gmail. — invalid.'),
('Only domain: @gmail.com — invalid.'),
('Only local: user@ — invalid.'),
('Empty:  — no.'),
('NULL — but we won’t insert NULL here, just empty string.'),
(''),
('                                                                 '),
('user@gmail.com и немного русского текста.'),
('Почта: admin@yandex.ru указана для связи.'),
('Напишите на support@mail.ru — мы ответим.'),
('user@gmail.com; admin@yandex.ru; support@mail.ru — через точку с запятой.'),
('user+filter@gmail.com — фильтр в Gmail.'),
('user.name+tag@yandex.ru — тоже поддерживается.'),
('user_name@mail.ru — нижнее подчёркивание разрешено.'),
('1user2@mail.ru — цифры в начале и середине — ок.'),
('x@gmail.com — короткий, но валидный.'),
('very.very.long.email.address@yandex.ru — длинный, но валидный.'),
('a.b.c.d.e.f.g.h.i.j.k.l.m.n.o.p.q.r.s.t.u.v.w.x.y.z@mail.ru'),
('!.#$%&''*+-/=?^_`{|}~@gmail.com — спецсимволы в local-part.'),
('user@yandex.ru., — с запятой и точкой после — email всё равно внутри.'),
('Email в середине предложения — например, user@gmail.com — должен быть извлечён.'),
('А если email в конце? — admin@yandex.ru'),
('А если в начале? support@mail.ru — вот он.'),
('user@gmail.com (primary), backup@yandex.ru (secondary).'),
('Main: user@mail.ru; Alt: none.'),
('Deprecated: postmaster@gmail.com still works.'),
('Abuse reports: abuse@yandex.ru are monitored.'),
('Security: security@mail.ru for vulnerabilities.'),
('Billing: billing@gmail.com for invoices.'),
('Support in Russian: поддержка@yandex.ru — но не латиница, не матчится.'),
('Support in English: support@yandex.ru — matches.'),
('CAPSLOCK: USER@MAIL.RU — still valid.'),
('mIxEd cAsE: UsEr@GmAiL.CoM — still valid.'),
('user@gmail.com,user2@yandex.ru,user3@mail.ru — comma separated.'),
('user@gmail.com; user2@yandex.ru; user3@mail.ru — semicolon separated.'),
('user@gmail.com | user2@yandex.ru | user3@mail.ru — pipe separated.'),
('user@gmail.com and user2@yandex.ru and user3@mail.ru — natural language.'),
('user@gmail.com. Next sentence starts here.'),
('user@gmail.com! Exclamation mark after.'),
('user@gmail.com? Question mark — still valid.'),
('Email: user@gmail.com — with prefix.'),
('→ user@yandex.ru ← with arrows.'),
('★ support@mail.ru ★ with stars.'),
('Email inside code: `user@gmail.com` — still valid.'),
('Email in comment: <!-- admin@yandex.ru --> — should be extracted.'),
('Email in script: console.log("user@mail.ru") — still an email.');