INSERT INTO social_posts (content) VALUES
('Люблю #PostgreSQL и #SQL! Это #круто.'),
('Мой первый пост #Hello_World #postgresql #Beginner'),
('Без хештегов вообще.'),
('#DataScience #MachineLearning #AI — будущее!'),
('#это-не-хештег, #this.is.bad, #what?nothing.'),
('#PostgreSQL #postgresql #PoStGrEs'),
('читайте книгу #DatabaseDesign, потом #SQL2024.'),
('#OneTag'),
('#SQL2024 #version_3_14 #tag123'),
('#data_engineer #back_end'),
('#db #sql #dev'),
('#tag! #tag? #tag.'),
('#базыданных #постгрес'),
('#data-science '),
('#web.dev '),
('#data science'),
('#😊 #🚀'),
('#PoStGrEsQl #sQlStAnDaRd'),
('#sql #SQL #Sql — все станут "sql".'),
('#this_is_a_very_long_hashtag_for_testing_purposes'),
('#123start'),
('#_private'),
('#__init__ #___'),
('#file/path'),
('#user@test.com '),
('//example.com '),
('#hash#tag'),
('#"quoted"'),
('#don''t'),
('#c++'),
('#key=value '),
('#tag,here'),
('#end;here'),
('here'),
('#func()'),
('#arr[]'),
('#dict{}'),
('#A&B'),
('#$money'),
('#100%'),
('#wild*card'),
('#user@host'),
('#end#'),
('##tag#'),
('#'),
('#
 '),
('#start here.'),
('ending with #finish'),
('text #middle text.'),
('#first #second #third.'),
('#aaa #___ #111.'),
('#café #naïve'),
('#tag😊 '),
('#tagПривет '),
('#alphaβ '),
('#pi≈3.14 '),
('#price$100'),
('#𝟙𝟚𝟛'),
('#v1_0_0 #build_20240517.'),
('#CamelCase #snake_case.'),
('#NASA #FBI #CIA.'),
('#v2_1_4 #release_3_0_0.'),
('#PR123 #ISSUE456 #BUG789.'),
('#JohnDoe #JaneSmith #User123.'),
('#NewYork #LosAngeles #SanFrancisco.'),
('#Python #JavaScript #TypeScript #Go #Rust #CSharp.'),
('#Docker #Kubernetes #AWS #Azure #GCP.'),
('#React #Vue #Angular #Svelte.'),
('#PostgreSQL #MySQL #MongoDB #Redis #SQLite.'),
('#Git #GitHub #GitLab #Bitbucket.'),
('#Linux #Windows #macOS #Ubuntu #CentOS.'),
('#Developer #DevOps #Admin #QA #Designer.'),
('#Agile #Scrum #Kanban #DevOps.'),
('#Conference2024 #Meetup #Hackathon.'),
('#iPhone #Android #MacBook #iPad.'),
('#Minecraft #Fortnite #AmongUs.'),
('#Avengers #StarWars #Matrix.'),
('#Rock #Jazz #HipHop #Classical.'),
('#1984 #Dune #Hobbit.'),
('#Tolkien #Asimov #King.'),
('#NewYear #Christmas #Halloween.'),
('#Summer #Winter #Spring #Autumn.'),
('#Sunny #Rainy #Snowy #Cloudy.'),
('#Pizza #Sushi #Burger #Coffee.'),
('#Tea #Beer #Wine #Whiskey.'),
('#Cat #Dog #Bird #Fish.'),
('#Tree #Flower #Grass #Rose.'),
('#Red #Blue #Green #Yellow.'),
('#Happy #Sad #Angry #Excited.'),
('#Running #Swimming #Reading #Coding.'),
('#Home #Work #School #Park #Beach.'),
('#Car #Bike #Bus #Train #Plane.'),
('#Shirt #Pants #Shoes #Hat.'),
('#Watch #Glasses #Bag #Wallet.'),
('#Football #Basketball #Tennis #Golf.'),
('#TeamA #TeamB #Champions.'),
('#Level1 #Stage2 #Phase3.'),
('#Active #Inactive #Pending #Done.'),
('#High #Medium #Low #Critical.'),
('#Important #Urgent #Later #Maybe.'),
('#Work #Personal #Finance #Health.'),
('#ProjectX #Alpha #Beta #Release.'),
('#Task1 #Todo #InProgress #Completed.'),
('#Idea #Concept #Prototype #Product.'),
('#Goal #Target #Objective #Result.'),
('#Dream #Wish #Hope #Future.'),
('#Memory #Nostalgia #Past #Childhood.'),
('#Plan #Schedule #Calendar #Deadline.'),
('#Success #Failure #Win #Lose.'),
('#Award #Prize #Medal #Trophy.'),
('#Top10 #BestSeller #Popular #Trending.'),
('#Review #Feedback #Comment #Rating.'),
('#Question #Ask #Help #Support.'),
('#Answer #Solution #Fix #Reply.');